### PR TITLE
Added Ogre Token

### PR DESCRIPTION
**Pull request by ErgoWhale**
Added Ogre token. We are a coin with over 5,000 followers and a lot of requests to be added to the DEX.

Please contact me with verification questions - cardanoergopool@gmail.com

### CODE REVIEW

**Comment by dilan015** [comment]
I believe this is a faithful project.The projector has a lot of attractions so hopefully the project will be better in the future and will be the best.

**Comment by Abefedude12** [comment]
I'm sure this is a legit and promising project.

**Comment by Balor44** [comment]
This is a step in the right direction and I'm sure many more good things will follow

**Comment by kmsami299** [comment]
List it please

**Review by yasha-black — APPROVED** [review]

**Comment by Succex14** [comment]
Let's gooooo 🔥💃

**Comment by realsedrick** [comment]
> 

This is awesome project 🔥🔥🔥🔥🔥

**Comment by Biggmo** [comment]
Great project

**Comment by Ciboyz** [comment]
very good

**Comment by zainal7797** [comment]
Good project

**Pull request merged**
